version: '3.2'

services:
  # app:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - ${APP_PORT}:3000
  #   command: npm run start:dev
  #   env_file:
  #     - .env
  #   networks:
  #     - appnet
  #   depends_on:
  #     - redis
  #     - postgres
  redis:
    image: redis:latest
    volumes:
      - .docker/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - appnet
  postgres:
    image: postgres:alpine
    networks:
      - appnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .docker/db:/var/lib/postgresql/data
networks:
  appnet:
